spring:
  application:
    name: propSmart
  profiles:
    active: local
  redis:
    database: 0
    host: 8.153.84.186
    port: 6379
  rabbitmq:
    host: 8.153.84.186
    port: 5672
    username: rabbitmq
    password: abc123
    listener:
      simple:
        acknowledge-mode: manual
    cache:
      connection:
        mode: channel
    dynamic: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/JCD
      username: root
      password: Sit@210411
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5

    postgresql:
      url: jdbc:postgresql://localhost:5432/JCD_OSM
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 5

  servlet:
    multipart:
      # 大小限制
      max-file-size: 50MB
server:
  address: 0.0.0.0
  port: 8601
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
    com.mrdotxin.propsmart.mapper: ERROR
    com.mrdotxin.propsmart.mapper.postgresql: ERROR
    org.mybatis: ERROR
# 一定要加, 不然swagger 功能会被默认ban掉
knife4j:
  enable: true

jwt-secret: MZJLZYZZZFYPYC

Bill-Generate-Interval: "0 0 2 1 * ?"
Elevator-Status-Generate-Interval: "0 3 * * * ?"
Energy-Consumption-Generate-Interval: "0 8 * * * ?"
Fire-Equipment-Inspection-Interval: "0 8 * * * ?"

update: 2