spring:
  application:
    name: iCloudCanvas
  profiles:
    active: local
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JCD
    username: root
    password: root
  servlet:
    multipart:
      # 大小限制
      max-file-size: 50MB
server:
  address: 0.0.0.0
  port: 8501
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 一定要加, 不然swagger 功能会被默认ban掉
knife4j:
  enable: true

jwt-secret: MZJLZYZZZFYPYC

Bill-Generate-Interval: "0 0 2 1 * ?"

Energy-Consumption-Generate-Interval: "0 0 * * * ?"
